### ISSUE TITLE
Erigon2 prototype is hanging

### ISSUE THREAD

**Issue by AlexeyAkhunov** [ledgerwatch/erigon-lib#252]
This is the result of `kill -6`
```
INFO[01-19|07:38:54.959] Processed                                blocks=4156000
INFO[01-19|07:39:27.326] Processed                                blocks=4157000
SIGABRT: abort
PC=0x7fff204958e2 m=0 sigcode=0

goroutine 0 [idle]:
runtime.pthread_cond_wait(0x593cf20, 0x593cee0)
	runtime/sys_darwin.go:393 +0x34
runtime.semasleep(0xffffffffffffffff)
	runtime/os_darwin.go:66 +0xad
runtime.notesleep(0x593ccd0)
	runtime/lock_sema.go:182 +0x85
runtime.mPark()
	runtime/proc.go:1441 +0x2a
runtime.stopm()
	runtime/proc.go:2408 +0x78
runtime.findrunnable()
	runtime/proc.go:2984 +0x865
runtime.schedule()
	runtime/proc.go:3367 +0x239
runtime.park_m(0xc0001b4b60)
	runtime/proc.go:3516 +0x14d
runtime.mcall()
	runtime/asm_amd64.s:307 +0x43

goroutine 1 [chan send, 242 minutes, locked to thread]:
github.com/ledgerwatch/erigon-lib/compress.reducedict.func3({0x7c003c42000, 0x14, 0x7c003c42000})
	github.com/ledgerwatch/erigon-lib@v0.0.0-20220118142005-340195df9375/compress/parallel_compress.go:247 +0x149
github.com/ledgerwatch/erigon-lib/compress.(*DecompressedFile).ForEach(0xc002b70140, 0x7c003ab0cc8)
	github.com/ledgerwatch/erigon-lib@v0.0.0-20220118142005-340195df9375/compress/compress.go:1429 +0x246
github.com/ledgerwatch/erigon-lib/compress.reducedict({0x4c96423, 0x4c94637}, {0xc003b2e000, 0x4b}, {0x7c00e1e22c0, 0x40}, {0xc00165f170, 0x23}, 0xc002b70140, 0x1)
	github.com/ledgerwatch/erigon-lib@v0.0.0-20220118142005-340195df9375/compress/parallel_compress.go:243 +0x7bd
github.com/ledgerwatch/erigon-lib/compress.(*Compressor).Compress(0x7c006f1c000)
	github.com/ledgerwatch/erigon-lib@v0.0.0-20220118142005-340195df9375/compress/compress.go:166 +0x748
github.com/ledgerwatch/erigon-lib/aggregator.btreeToFile(0x7c00714f290, {0x7c00e1e20c0, 0x7c00714f320}, {0xc00165f170, 0x3})
	github.com/ledgerwatch/erigon-lib@v0.0.0-20220118142005-340195df9375/aggregator/aggregator.go:724 +0x199
github.com/ledgerwatch/erigon-lib/aggregator.(*Changes).aggregate(0xc00024d680, 0x4c9651d, 0x7c0072cce28, 0x4c914d0, {0x5191240, 0x7c005362270}, {0x4c95245, 0x9}, 0x0)
	github.com/ledgerwatch/erigon-lib@v0.0.0-20220118142005-340195df9375/aggregator/aggregator.go:553 +0x93f
github.com/ledgerwatch/erigon-lib/aggregator.(*Writer).aggregateUpto(0xc000510000, 0x3e0000, 0x3e0fff)
	github.com/ledgerwatch/erigon-lib@v0.0.0-20220118142005-340195df9375/aggregator/aggregator.go:1949 +0xbc5
github.com/ledgerwatch/erigon-lib/aggregator.(*Writer).Aggregate(0xc000510000, 0x0)
	github.com/ledgerwatch/erigon-lib@v0.0.0-20220118142005-340195df9375/aggregator/aggregator.go:1623 +0x8b
github.com/ledgerwatch/erigon/cmd/state/commands.Erigon2(0xc0002e6a90, {0x5180320, 0xc000304340})
	github.com/ledgerwatch/erigon/cmd/state/commands/erigon2.go:213 +0x1728
github.com/ledgerwatch/erigon/cmd/state/commands.glob..func4(0x592a580, {0x4c90075, 0x4, 0x4})
	github.com/ledgerwatch/erigon/cmd/state/commands/erigon2.go:53 +0x9f
github.com/spf13/cobra.(*Command).execute(0x592a580, {0xc000491dc0, 0x4, 0x4})
	github.com/spf13/cobra@v1.2.1/command.go:856 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0x592aa80)
	github.com/spf13/cobra@v1.2.1/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.2.1/command.go:902
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	github.com/spf13/cobra@v1.2.1/command.go:895
github.com/ledgerwatch/erigon/cmd/state/commands.Execute()
	github.com/ledgerwatch/erigon/cmd/state/commands/root.go:83 +0x52
main.main()
	github.com/ledgerwatch/erigon/cmd/state/main.go:8 +0x17

goroutine 19 [sleep, 2 minutes]:
time.Sleep(0x22ecb25c00)
	runtime/time.go:193 +0x12e
github.com/VictoriaMetrics/metrics.summariesSwapCron(0x45d964b800)
	github.com/VictoriaMetrics/metrics@v1.18.1/summary.go:237 +0x36
created by github.com/VictoriaMetrics/metrics.registerSummaryLocked
	github.com/VictoriaMetrics/metrics@v1.18.1/summary.go:211 +0x127

goroutine 26 [select, 1250 minutes]:
github.com/ledgerwatch/erigon/internal/debug.ListenSignals({0x0, 0x0})
	github.com/ledgerwatch/erigon/internal/debug/signal.go:26 +0x1e5
created by github.com/ledgerwatch/erigon/internal/debug.SetupCobra
	github.com/ledgerwatch/erigon/internal/debug/flags.go:145 +0x174

goroutine 25 [select, 1250 minutes]:
github.com/ledgerwatch/erigon/cmd/state/commands.rootContext.func1()
	github.com/ledgerwatch/erigon/cmd/state/commands/root.go:36 +0x152
created by github.com/ledgerwatch/erigon/cmd/state/commands.rootContext
	github.com/ledgerwatch/erigon/cmd/state/commands/root.go:31 +0x9d

goroutine 13 [syscall, 1250 minutes]:
os/signal.signal_recv()
	runtime/sigqueue.go:166 +0x28
os/signal.loop()
	os/signal/signal_unix.go:24 +0x19
created by os/signal.Notify.func1.1
	os/signal/signal.go:151 +0x2c

goroutine 50 [chan receive, 1250 minutes]:
github.com/ledgerwatch/erigon/cmd/state/commands.Erigon2.func1()
	github.com/ledgerwatch/erigon/cmd/state/commands/erigon2.go:63 +0x28
created by github.com/ledgerwatch/erigon/cmd/state/commands.Erigon2
	github.com/ledgerwatch/erigon/cmd/state/commands/erigon2.go:62 +0x145

goroutine 8873 [runnable]:
github.com/ledgerwatch/erigon-lib/compress.optimiseCluster(0x0, {0x7c001236c1e, 0xa, 0xa}, {0xc000474608, 0x16, 0x16}, 0x0, 0xc001d81d00, {0x7c00122c000, ...}, ...)
	github.com/ledgerwatch/erigon-lib@v0.0.0-20220118142005-340195df9375/compress/parallel_compress.go:132 +0xa35
github.com/ledgerwatch/erigon-lib/compress.reduceDictWorker(0x7c0072960c0, 0x7c0038ce320, 0xc00020a8d0, 0xc0000b7450, 0x7c0038ce310, 0x7c0038ce318, 0x7c003aa76b0)
	github.com/ledgerwatch/erigon-lib@v0.0.0-20220118142005-340195df9375/compress/parallel_compress.go:188 +0x4b3
created by github.com/ledgerwatch/erigon-lib/compress.reducedict
	github.com/ledgerwatch/erigon-lib@v0.0.0-20220118142005-340195df9375/compress/parallel_compress.go:240 +0x405

```

**Comment by AlexeyAkhunov** [comment]
Comment from @AskAlexSharov:

looks as infinity loop
```
    for patternIdx != 0 {
        patternCount++
        patternIdx = patterns[patternIdx+1]
    }
```

I took it as is from hack.go 
maybe just need compare it with `CompressorSequential.findMatches` side-by-side
